/*
    En un centro metereologico se llevan los promedios mensuales
    de las lluvias caidas en las principales regiones del pais.
    NORTE,CENTRO Y SUR. Escriba un algoritmo para calcular lo siguiente:
    a)El promedio anual de la region centro
    b)El mes y region con menor lluvia 
    c)La region con mayor lluvia anual
 */
package SESION_02_JOPTION;

import MenuFormulario.Apertura;

/**
 *
 * @author Sistemas
 */
public class EJERCICIO_J7 extends javax.swing.JFrame {

    /**
     * Creates new form EJERCICIO_07
     */
    public EJERCICIO_J7() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumN = new javax.swing.JTextField();
        btnIngresarN = new javax.swing.JButton();
        lblMensajeN = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        atAreaN = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atArea = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumC = new javax.swing.JTextField();
        btnIngresarC = new javax.swing.JButton();
        lblMensajeC = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        atAreaC = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNumS = new javax.swing.JTextField();
        btnIngresarS = new javax.swing.JButton();
        lblMensajeS = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        atAreaS = new javax.swing.JTextArea();
        btnCalcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Norte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Monto");

        txtNumN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumNActionPerformed(evt);
            }
        });

        btnIngresarN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngresarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadir_48.png"))); // NOI18N
        btnIngresarN.setText("Ingresar");
        btnIngresarN.setBorderPainted(false);
        btnIngresarN.setContentAreaFilled(false);
        btnIngresarN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresarN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadir_48.png"))); // NOI18N
        btnIngresarN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadir_64.png"))); // NOI18N
        btnIngresarN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIngresarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarNActionPerformed(evt);
            }
        });

        lblMensajeN.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        lblMensajeN.setForeground(new java.awt.Color(255, 51, 51));

        atAreaN.setColumns(20);
        atAreaN.setRows(5);
        jScrollPane4.setViewportView(atAreaN);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 29, Short.MAX_VALUE)
                                .addComponent(lblMensajeN, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(txtNumN, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIngresarN, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNumN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMensajeN, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnIngresarN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, 440, 190));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/climas.gif"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -10, 230, 270));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 255), 2));

        atArea.setColumns(20);
        atArea.setRows(5);
        atArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255), 2));
        jScrollPane1.setViewportView(atArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 360, 370));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar48.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar48.png"))); // NOI18N
        btnLimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar64.png"))); // NOI18N
        btnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 570, 110, 90));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar48.png"))); // NOI18N
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar48.png"))); // NOI18N
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar64.png"))); // NOI18N
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 110, 90));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Centro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 18))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Monto");

        txtNumC.setEnabled(false);
        txtNumC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCActionPerformed(evt);
            }
        });

        btnIngresarC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngresarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadir_48.png"))); // NOI18N
        btnIngresarC.setText("Ingresar");
        btnIngresarC.setBorderPainted(false);
        btnIngresarC.setContentAreaFilled(false);
        btnIngresarC.setEnabled(false);
        btnIngresarC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresarC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadir_48.png"))); // NOI18N
        btnIngresarC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadir_64.png"))); // NOI18N
        btnIngresarC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIngresarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarCActionPerformed(evt);
            }
        });

        lblMensajeC.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        lblMensajeC.setForeground(new java.awt.Color(255, 51, 51));

        atAreaC.setColumns(20);
        atAreaC.setRows(5);
        jScrollPane5.setViewportView(atAreaC);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumC, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMensajeC, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresarC, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresarC)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNumC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMensajeC, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Sur", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 18))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Monto");

        txtNumS.setEnabled(false);
        txtNumS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumSActionPerformed(evt);
            }
        });

        btnIngresarS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngresarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadir_48.png"))); // NOI18N
        btnIngresarS.setText("Ingresar");
        btnIngresarS.setAutoscrolls(true);
        btnIngresarS.setBorderPainted(false);
        btnIngresarS.setContentAreaFilled(false);
        btnIngresarS.setEnabled(false);
        btnIngresarS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresarS.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadir_48.png"))); // NOI18N
        btnIngresarS.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadir_64.png"))); // NOI18N
        btnIngresarS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIngresarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarSActionPerformed(evt);
            }
        });

        lblMensajeS.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        lblMensajeS.setForeground(new java.awt.Color(255, 51, 51));

        atAreaS.setColumns(20);
        atAreaS.setRows(5);
        jScrollPane6.setViewportView(atAreaS);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumS, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMensajeS, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIngresarS, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNumS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMensajeS, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnIngresarS))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 440, 200));

        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calculadora_48.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setBorderPainted(false);
        btnCalcular.setContentAreaFilled(false);
        btnCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalcular.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calculadora_48.png"))); // NOI18N
        btnCalcular.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calculadora64.png"))); // NOI18N
        btnCalcular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, 112, 90));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel4.setText("promedio de lluvias");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255), 2));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 380, 390));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDO.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumNActionPerformed
    static int band,band1,min,mes,max,i,menor_mes,j,iN=0,iC=0,iS=0;
    static int  minN,maxN,minC,maxC,minS,maxS;
    static int suma_Norte=0,suma_Centro=0,suma_Sur=0;
    static String region_menor,region_mayor;
    private void btnIngresarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarNActionPerformed
        mes=Integer.parseInt(txtNumN.getText());
        atAreaN.append("Mes "+(iN+1)+" es: "+mes+"\n");
        suma_Norte+=mes;
        minimo();
        maximo();
        iN++;
        lblMensajeN.setText(iN+"meses ingresados");
        txtNumN.setText("");
        txtNumN.requestFocus();
        if(iN==12){
            txtNumN.setEnabled(false);
            btnIngresarN.setEnabled(false);
            txtNumC.setEnabled(true);
            btnIngresarC.setEnabled(true);
            lblMensajeN.setText("Total de meses ingresado");
            minN=min;
            maxN=max;
            band=0;
            band1=0;
            min=0;
            max=0;
        }
    }//GEN-LAST:event_btnIngresarNActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNumN.setEnabled(true);
        btnIngresarN.setEnabled(true);
        txtNumC.setEnabled(true);
        btnIngresarC.setEnabled(true);
        txtNumS.setEnabled(true);
        btnIngresarS.setEnabled(true);
        lblMensajeN.setText("");
        lblMensajeC.setText("");
        lblMensajeS.setText("");
        atArea.setText("");
        atAreaN.setText("");
        atAreaC.setText("");
        atAreaS.setText("");
        txtNumN.setText("");
        txtNumC.setText("");
        txtNumS.setText("");
        txtNumN.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Apertura op=new Apertura();
        op.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNumCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCActionPerformed

    private void btnIngresarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarCActionPerformed
        mes=Integer.parseInt(txtNumC.getText());
        atAreaC.append("Mes "+(iC+1)+" es: "+mes+"\n");
        suma_Centro+=mes;
        minimo();
        maximo();
        iC++;
        lblMensajeC.setText(iC+" meses ingresados");
        txtNumC.setText("");
        txtNumC.requestFocus();
        if(iC==12){
            txtNumC.setEnabled(false);
            btnIngresarC.setEnabled(false);
            txtNumS.setEnabled(true);
            btnIngresarS.setEnabled(true);
            lblMensajeC.setText("Total de meses ingresado");
            minC=min;
            maxC=max;
            band=0;
            band1=0;
            min=0;
            max=0;
        }
    }//GEN-LAST:event_btnIngresarCActionPerformed

    private void txtNumSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumSActionPerformed

    private void btnIngresarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarSActionPerformed
        mes=Integer.parseInt(txtNumS.getText());
        atAreaS.append("Mes "+(iS+1)+" es: "+mes+"\n");
        suma_Sur+=mes; 
        minimo();
        maximo();
        iS++;
        lblMensajeS.setText(iS+"meses ingresados");
        txtNumS.setText("");
        txtNumS.requestFocus();
        if(iS==12){
            txtNumS.setEnabled(false);
            btnIngresarS.setEnabled(false);
            lblMensajeS.setText("Total de meses ingresado");
            minS=min;
            maxS=max;
            band=0;
            band1=0;
            min=0;
            max=0;
        }
    }//GEN-LAST:event_btnIngresarSActionPerformed

    private static void minimo() {
        if (band==0) {
            min=mes;
            band++;
        }
        if (mes<min) {
            min=mes;
            menor_mes=i;
        }
    }
    
    private static void maximo() {
        if (band1==0) {
            max=mes;
            band1++;
        }
        if (mes>max) {
            max=mes;
        }
    }

    private static void menor_lluvia() {
     int menor_lluvia;
       menor_lluvia=minN;
       region_menor="Norte";
        if (minC<menor_lluvia) {
            menor_lluvia=minC;
            region_menor="Centro";
        }
        if (minS<menor_lluvia) {
            menor_lluvia=minS;
            region_menor="Sur";
        }
    }
    
    private static void mayor_lluvia() {
        int mayor_anual,N,C,S;
        N=suma_Norte/12;
        C=suma_Centro/12;
        S=suma_Sur/12;
        mayor_anual=N;
        region_mayor="Norte";
        if (C>mayor_anual) {
            mayor_anual=C;
            region_mayor="Centro";
        }
        if (S>mayor_anual) {
            mayor_anual=S;
            region_mayor="Sur";
        }
    }

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        menor_lluvia();
        mayor_lluvia();
        atArea.append("El menor monto fue: "+minN+"\n\n");
        atArea.append("RESULTADOS\n\n1.- El promedio Anual de la region Centro es: "+(suma_Centro/12)+
                "\n2.- La region con menor lluvia es: "+region_menor+" y el mes "+menor_mes+"\n3.- La region con mayor lluvia anual es: "+region_mayor);
    }//GEN-LAST:event_btnCalcularActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EJERCICIO_J7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atArea;
    private javax.swing.JTextArea atAreaC;
    private javax.swing.JTextArea atAreaN;
    private javax.swing.JTextArea atAreaS;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnIngresarC;
    private javax.swing.JButton btnIngresarN;
    private javax.swing.JButton btnIngresarS;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblMensajeC;
    private javax.swing.JLabel lblMensajeN;
    private javax.swing.JLabel lblMensajeS;
    private javax.swing.JTextField txtNumC;
    private javax.swing.JTextField txtNumN;
    private javax.swing.JTextField txtNumS;
    // End of variables declaration//GEN-END:variables
}
